import { Routes } from '@angular/router';

export const routes: Routes = [
  { path: '', loadComponent: () => import('./pages/home/home.component').then((m) => m.HomeComponent), pathMatch: 'full' },
  { path: 'general_cleaning_roads', redirectTo: 'road_maintenance', pathMatch: 'full' },
  { path: 'general_cleaning_roads.html', redirectTo: 'road_maintenance', pathMatch: 'full' },
  { path: 'road_cleaning_maintenance', redirectTo: 'road_maintenance', pathMatch: 'full' },
  { path: 'road_cleaning_maintenance.html', redirectTo: 'road_maintenance', pathMatch: 'full' },
  { path: 'about.html', redirectTo: 'about', pathMatch: 'full' },
  { path: 'administrative_building_cleaning.html', redirectTo: 'administrative_building_cleaning', pathMatch: 'full' },
  { path: 'board.html', redirectTo: 'board', pathMatch: 'full' },
  { path: 'building_cleaning_work.html', redirectTo: 'building_cleaning_work', pathMatch: 'full' },
  { path: 'building_facilities_maintenance.html', redirectTo: 'building_facilities_maintenance', pathMatch: 'full' },
  { path: 'careers.html', redirectTo: 'careers', pathMatch: 'full' },
  { path: 'certificates.html', redirectTo: 'certificates', pathMatch: 'full' },
  { path: 'chairman_message.html', redirectTo: 'chairman_message', pathMatch: 'full' },
  { path: 'communication-complaints.html', redirectTo: 'communication-complaints', pathMatch: 'full' },
  { path: 'company_goals.html', redirectTo: 'company_goals', pathMatch: 'full' },
  { path: 'contracting.html', redirectTo: 'contracting', pathMatch: 'full' },
  { path: 'contracting_transport.html', redirectTo: 'contracting_transport', pathMatch: 'full' },
  { path: 'equipment.html', redirectTo: 'equipment', pathMatch: 'full' },
  { path: 'garden_lighting_maintenance.html', redirectTo: 'garden_lighting_maintenance', pathMatch: 'full' },
  { path: 'green_area_maintenance.html', redirectTo: 'green_area_maintenance', pathMatch: 'full' },
  { path: 'maintenance_of_electric_elevators.html', redirectTo: 'maintenance_of_electric_elevators', pathMatch: 'full' },
  { path: 'previous_works.html', redirectTo: 'previous_works', pathMatch: 'full' },
  { path: 'project.html', redirectTo: 'project', pathMatch: 'full' },
  { path: 'project_dar.html', redirectTo: 'project_dar', pathMatch: 'full' },
  { path: 'project_janna.html', redirectTo: 'project_janna', pathMatch: 'full' },
  { path: 'project_social.html', redirectTo: 'project_social', pathMatch: 'full' },
  { path: 'project_t_square.html', redirectTo: 'project_t_square', pathMatch: 'full' },
  { path: 'protocol-tameer-ahly-misr.html', redirectTo: 'protocol-tameer-ahly-misr', pathMatch: 'full' },
  { path: 'real_estate_development.html', redirectTo: 'real_estate_development', pathMatch: 'full' },
  { path: 'road_maintenance.html', redirectTo: 'road_maintenance', pathMatch: 'full' },
  { path: 'security_and_guarding_work.html', redirectTo: 'security_and_guarding_work', pathMatch: 'full' },
  { path: 'services.html', redirectTo: 'services', pathMatch: 'full' },
  { path: 'sewage_network_maintenance.html', redirectTo: 'sewage_network_maintenance', pathMatch: 'full' },
  {
    path: '',
    loadComponent: () => import('./layout/inner-layout.component').then((m) => m.InnerLayoutComponent),
    children: [
      { path: 'about', loadComponent: () => import('./pages/about/about.component').then((m) => m.AboutComponent) },
      { path: 'administrative_building_cleaning', loadComponent: () => import('./pages/administrative-building-cleaning/administrative-building-cleaning.component').then((m) => m.AdministrativeBuildingCleaningComponent) },
      { path: 'board', loadComponent: () => import('./pages/board/board.component').then((m) => m.BoardComponent) },
      { path: 'building_cleaning_work', loadComponent: () => import('./pages/building-cleaning-work/building-cleaning-work.component').then((m) => m.BuildingCleaningWorkComponent) },
      { path: 'building_facilities_maintenance', loadComponent: () => import('./pages/building-facilities-maintenance/building-facilities-maintenance.component').then((m) => m.BuildingFacilitiesMaintenanceComponent) },
      { path: 'careers', loadComponent: () => import('./pages/careers/careers.component').then((m) => m.CareersComponent) },
      { path: 'certificates', loadComponent: () => import('./pages/certificates/certificates.component').then((m) => m.CertificatesComponent) },
      { path: 'chairman_message', loadComponent: () => import('./pages/chairman-message/chairman-message.component').then((m) => m.ChairmanMessageComponent) },
      { path: 'communication-complaints', loadComponent: () => import('./pages/communication-complaints/communication-complaints.component').then((m) => m.CommunicationComplaintsComponent) },
      { path: 'company_goals', loadComponent: () => import('./pages/company-goals/company-goals.component').then((m) => m.CompanyGoalsComponent) },
      { path: 'contracting', loadComponent: () => import('./pages/contracting/contracting.component').then((m) => m.ContractingComponent) },
      { path: 'contracting_transport', loadComponent: () => import('./pages/contracting-transport/contracting-transport.component').then((m) => m.ContractingTransportComponent) },
      { path: 'equipment', loadComponent: () => import('./pages/equipment/equipment.component').then((m) => m.EquipmentComponent) },
      { path: 'garden_lighting_maintenance', loadComponent: () => import('./pages/garden-lighting-maintenance/garden-lighting-maintenance.component').then((m) => m.GardenLightingMaintenanceComponent) },
      { path: 'green_area_maintenance', loadComponent: () => import('./pages/green-area-maintenance/green-area-maintenance.component').then((m) => m.GreenAreaMaintenanceComponent) },
      { path: 'maintenance_of_electric_elevators', loadComponent: () => import('./pages/maintenance-of-electric-elevators/maintenance-of-electric-elevators.component').then((m) => m.MaintenanceOfElectricElevatorsComponent) },
      { path: 'previous_works', loadComponent: () => import('./pages/previous-works/previous-works.component').then((m) => m.PreviousWorksComponent) },
      { path: 'project', loadComponent: () => import('./pages/project/project.component').then((m) => m.ProjectComponent) },
      { path: 'project_dar', loadComponent: () => import('./pages/project-dar/project-dar.component').then((m) => m.ProjectDarComponent) },
      { path: 'project_janna', loadComponent: () => import('./pages/project-janna/project-janna.component').then((m) => m.ProjectJannaComponent) },
      { path: 'project_social', loadComponent: () => import('./pages/project-social/project-social.component').then((m) => m.ProjectSocialComponent) },
      { path: 'project_t_square', loadComponent: () => import('./pages/project-t-square/project-t-square.component').then((m) => m.ProjectTSquareComponent) },
      { path: 'protocol-tameer-ahly-misr', loadComponent: () => import('./pages/protocol-tameer-ahly-misr/protocol-tameer-ahly-misr.component').then((m) => m.ProtocolTameerAhlyMisrComponent) },
      { path: 'real_estate_development', loadComponent: () => import('./pages/real-estate-development/real-estate-development.component').then((m) => m.RealEstateDevelopmentComponent) },
      { path: 'road_maintenance', loadComponent: () => import('./pages/road-maintenance/road-maintenance.component').then((m) => m.RoadMaintenanceComponent) },
      { path: 'security_and_guarding_work', loadComponent: () => import('./pages/security-and-guarding-work/security-and-guarding-work.component').then((m) => m.SecurityAndGuardingWorkComponent) },
      { path: 'services', loadComponent: () => import('./pages/services/services.component').then((m) => m.ServicesComponent) },
      { path: 'sewage_network_maintenance', loadComponent: () => import('./pages/sewage-network-maintenance/sewage-network-maintenance.component').then((m) => m.SewageNetworkMaintenanceComponent) },
      { path: '**', loadComponent: () => import('./pages/not-found/not-found.component').then((m) => m.NotFoundComponent) },
    ],
  },
];
